// uu5-ruby-1.8.0
var buildHelpers = require("./helpers.js");

var config = require("../.tmp/config.json"); // generated by tools/build-uc.js

// each "pack" in "config" must be built separately
var packs = config.packs || [config];
var webpackConfig = packs.reduce((result, pack) => {
  if (!pack) return result;

  var packConfig = Object.assign({}, config, pack);
  delete packConfig.packs;
  if (result.length === 0) packConfig.copyFiles = true; // use copy plugin only for 1st invocation so that it isn't invoked for each built JS file
  var packWebpackConfig = buildHelpers.getWebpackConfig(packConfig);
  return result.concat(packWebpackConfig);
}, []);

// add "project packages" to the build
var packages = buildHelpers.getProjectPackageList(config.sourcePath);
webpackConfig = packages.reduce((r, pack) => r.concat(buildHelpers.getWebpackConfig(Object.assign({}, config, {
  outputFile: pack.name + "/" + pack.name + (config.minify ? ".min" : "") + ".js",
  entryPoints: [pack.entryPoint]
}))), webpackConfig);

module.exports = webpackConfig;
